### ISSUE TITLE
Make A Navbar For Landing Page Favela Website

### ISSUE THREAD

**Issue by RamaAlqdri** [LaFavela/favela#2]
From 21st March till 26th March 2023

**Comment by VosMovok** [comment]
Will do

**Comment by VosMovok** [comment]
@RamaAlqdri I'm sorry for the assignment for the current task, you only assign my task. How about yours what do you want to do?

**Comment by VosMovok** [comment]
fix #7956b05

**Comment by VosMovok** [comment]
#7956b05

**Comment by VosMovok** [comment]
#7956b05a6f634a81a70b5f7d561bf5e58faa0926 progress

**Comment by VosMovok** [comment]
7956b05a6f634a81a70b5f7d561bf5e58faa0926 progress
